---
deployment:
  tasks:
    - export DEPLOYPATH=$HOME/bondmetrics.pro
    - /bin/cp -R server $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp *.html $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
